/*  Copyright (c) MediaArea.net SARL. All Rights Reserved.
 *
 *  Use of this source code is governed by a BSD-style license that can
 *  be found in the License.html file in the root of the source tree.
 */

// Generated by Google Gemini 3 Flash

package net.mediaarea.mediainfo.tv

import androidx.lifecycle.ViewModel
import androidx.lifecycle.ViewModelProvider
import androidx.lifecycle.viewModelScope
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

class MediaViewModel(private val repository: MediaRepository) : ViewModel() {

    private val _uiState = MutableStateFlow<MediaUiState>(MediaUiState.Loading)
    val uiState: StateFlow<MediaUiState> = _uiState.asStateFlow()

    fun loadMedia() {
        viewModelScope.launch {
            _uiState.value = MediaUiState.Loading
            try {
                val items = repository.fetchMedia()
                if (items.isEmpty()) {
                    _uiState.value = MediaUiState.Empty
                } else {
                    _uiState.value = MediaUiState.Success(items)
                }
            } catch (e: Exception) {
                _uiState.value = MediaUiState.Error(e.message ?: "Unknown Error")
            }
        }
    }
}

class MediaViewModelFactory(private val repository: MediaRepository) : ViewModelProvider.Factory {
    override fun <T : ViewModel> create(modelClass: Class<T>): T {
        if (modelClass.isAssignableFrom(MediaViewModel::class.java)) {
            @Suppress("UNCHECKED_CAST")
            return MediaViewModel(repository) as T
        }
        throw IllegalArgumentException("Unknown ViewModel class")
    }
}

sealed class MediaUiState {
    object Loading : MediaUiState()
    object Empty : MediaUiState()
    data class Success(val items: List<MediaItem>) : MediaUiState()
    data class Error(val message: String) : MediaUiState()
}