name: Test Build

on:
  push:

env:
  QT_VER: 6.*

jobs:

  Build:

    runs-on: windows-latest

    steps:

      - name: Checkout zlib
        uses: actions/checkout@v4
        with:
          repository: MediaArea/zlib
          path: zlib

      - name: Checkout ZenLib
        uses: actions/checkout@v4
        with:
          repository: MediaArea/ZenLib
          path: ZenLib

      - name: Checkout MediaArea-Utils-Binaries for 7-Zip and libcurl
        uses: actions/checkout@v4
        with:
          repository: MediaArea/MediaArea-Utils-Binaries
          path: MediaArea-Utils-Binaries
          sparse-checkout: |
            Windows/7-Zip
            Windows/libcurl

      - name: Checkout MediaInfo-Graph-Plugin
        uses: actions/checkout@v4
        with:
          repository: MediaArea/MediaInfo-Graph-Plugin
          path: MediaInfo-Graph-Plugin

      - name: Checkout MediaInfo-Graph-Plugin-Binaries
        uses: actions/checkout@v4
        with:
          repository: MediaArea/MediaInfo-Graph-Plugin-Binaries
          path: MediaInfo-Graph-Plugin-Binaries

      - name: Checkout MediaInfoLib
        uses: actions/checkout@v4
        with:
          repository: MediaArea/MediaInfoLib
          path: MediaInfoLib

      - name: Checkout MediaInfo
        uses: actions/checkout@v4
        with:
          path: MediaInfo

      - name: Obtain FFmpeg
        run: |
          New-Item -Name "FFmpeg" -ItemType "directory"
          Invoke-WebRequest -Uri "https://mediaarea.net/download/snapshots/binary/ffmpeg/latest/FFmpeg_Bin_Latest_Windows_Static_x64.zip" -OutFile "FFmpeg\ffmpeg.zip"
          Expand-Archive -Path "FFmpeg\ffmpeg.zip" -DestinationPath "FFmpeg\ffmpeg"
          Copy-Item "FFmpeg\ffmpeg\bin\ffmpeg.exe" -Destination "FFmpeg\ffmpeg.exe"

      - name: Set-up Qt x64
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VER }}
          tools: 'tools_qtcreator,qt.tools.qtcreator'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build CLI
        shell: cmd
        run: |
          MSBuild -t:MediaInfo-CLI -p:Configuration=Release -p:Platform=x64 ${{ github.workspace }}\MediaInfo\Project\MSVC2022\MediaInfo.sln
          pushd ${{ github.workspace }}\MediaInfo\Release
          call Release_CLI_Windows_x64.bat
          popd

      - name: Copy Qt GUI dependencies
        shell: cmd
        run: |
          xcopy /y ${{ github.workspace }}\MediaInfo\Project\MSVC2022\x64\Release\ZenLib.lib ${{ github.workspace }}\ZenLib\Project\MSVC2022\x64\Release\
          xcopy /y ${{ github.workspace }}\MediaInfo\Project\MSVC2022\x64\Release\MediaInfo-Static.lib ${{ github.workspace }}\MediaInfoLib\Project\MSVC2022\x64\Release\

      - name: Restore Nuget packages for Shell Extension
        shell: cmd
        run: |
          curl -O https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
          nuget restore ${{ github.workspace }}\MediaInfo\Project\MSVC2022\MediaInfo.sln

      - name: Build Qt GUI
        shell: cmd
        run: |
          set QT_PATH=${{ env.QT_ROOT_DIR }}
          set QT_TOOLS_PATH=${{ env.IQTA_TOOLS }}
          set FFMPEG_EXE=${{ github.workspace }}\FFmpeg\ffmpeg.exe
          call ${{ github.workspace }}\MediaInfo\Release\Release_GUI_Qt_Windows_x64_MSIX.cmd

      - name: List repos and hashes for version info
        run: |
          # Initialize an empty array to store results
          $repo_info_list = @()
          # Define the folders containing the different repositories
          $folders = @('MediaInfo', 'MediaInfoLib', 'MediaInfo-Graph-Plugin', 'MediaInfo-Graph-Plugin-Binaries', 'MediaArea-Utils-Binaries', 'ZenLib', 'zlib')
          # Iterate over each folder
          foreach ($folder in $folders) {
            # Check if the folder exists
            if (Test-Path $folder) {
              # Change directory to the repo folder
              Set-Location $folder
              # Check if it's a valid git repository
              if (Test-Path ".git") {
                # Get the repository name (user/repo format)
                $repo_url = git config --get remote.origin.url
                $repo_name = ($repo_url -replace '.git$', '').Split('/')[-2..-1] -join '/'
                # Get the current Git commit hash
                $git_hash = git rev-parse HEAD
                # Format the output as "user/repo @ <hash>"
                $repo_info = "$repo_name @ $git_hash"
                $repo_info_list += $repo_info
              }
              # Go back to the root directory after processing the repo folder
              Set-Location ..
            }
          }
          # Write the list of repos and hashes to a text file
          $repo_info_list | Out-File -FilePath version_info.txt -Encoding utf8

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MediaInfo test build
          path: |
            ${{ github.workspace }}\MediaInfo\Release\MediaInfo_CLI_Windows_x64.zip
            ${{ github.workspace }}\MediaInfo\Release\MediaInfo_Qt_Windows_x64.msix
            ${{ github.workspace }}\version_info.txt
